name: GitHub Pages Deployment

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - run: tree -L 3
      - run: git branch
      - name: Set git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit built into docs
        run: |
          git add docs/
          git commit -m "Build #${{ github.run_number }}"
          git push origin master
