name: GitHub Pages Deployment

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - run: ls
      - name: Push build to *page* branch
        #run: git subtree push --prefix dist origin page
        run: git checkout page && git brach && git checkout master dist
